import React, { useState } from 'react';
import { X, FileText, Download, CheckCircle, Cpu, Info } from 'lucide-react';

export interface ChangeReportStats {
  changed_pixels: number;
  total_pixels: number;
  change_percentage: number;
  threshold?: number;
  input_width: number;
  input_height: number;
  after_width?: number;
  after_height?: number;
  mask_width?: number;
  mask_height?: number;
  tiled_inference_enabled?: boolean;
  tile_size?: number;
  tile_overlap?: number;
  tile_count?: number;
}

interface WorkspaceReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysisType: 'single' | 'change';
  stats?: ChangeReportStats | null;
  beforeImg?: string;
  afterImg?: string;
  maskImg?: string;
}

export const WorkspaceReportModal: React.FC<WorkspaceReportModalProps> = ({
  isOpen,
  onClose,
  stats,
  beforeImg,
  afterImg,
  maskImg,
}) => {
  const [downloading, setDownloading] = useState(false);

  if (!isOpen) return null;

  const now = new Date();
  const timestampStr = now.toISOString().replace('T', ' ').substring(0, 19) + ' UTC';

  const changedPixels = stats?.changed_pixels ?? 0;
  const totalPixels = stats?.total_pixels ?? 65536;
  const changePercentage = stats?.change_percentage ?? 0;
  const thresholdVal = stats?.threshold ?? 0.50;
  const isTiled = stats?.tiled_inference_enabled ?? false;
  const tileCount = stats?.tile_count ?? 1;
  const tileSize = stats?.tile_size ?? 256;
  const tileOverlap = stats?.tile_overlap ?? 0;
  const inputDim = stats ? `${stats.input_width} × ${stats.input_height} px` : '256 × 256 px';
  const maskDim = stats?.mask_width ? `${stats.mask_width} × ${stats.mask_height} px` : '256 × 256 px';
  const tiledDesc = isTiled ? `Enabled (${tileCount} tiles, ${tileSize}×${tileSize} px, overlap=${tileOverlap} px)` : 'Disabled (single native pass)';

  const handleDownload = () => {
    setDownloading(true);
    setTimeout(() => {
      setDownloading(false);
      const dossierContent = `=================================================================
SATQUERY AI — CHANGEFORMER ANALYSIS REPORT
=================================================================
AI Model:             ChangeFormer V6 (LEVIR-CD Swin-Transformer ViT)
Inference Mode:       ${tiledDesc}
Decision Threshold:   ${thresholdVal.toFixed(2)}
Inference Status:     ChangeFormer inference completed
Timestamp:            ${timestampStr}

INPUT & RESOLUTION:
- Input Acquisition:  ${inputDim}
- Mask Output Grid:   ${maskDim}
- Evaluated Pixels:   ${totalPixels.toLocaleString()}
- Tiled Inference:    ${tiledDesc}

CHANGE METRICS (REAL MODEL OUTPUT):
- Changed Pixels:     ${changedPixels.toLocaleString()}
- Total Pixels:       ${totalPixels.toLocaleString()}
- Change Percentage:  ${changePercentage}%
- Decision Threshold: ${thresholdVal.toFixed(2)}
- Surface Status:     ${changedPixels > 0 ? 'Change Detected' : 'No change detected by ChangeFormer at current threshold'}
- Ground Area (km²):  Area in km² unavailable — geographic resolution metadata was not provided.

Generated by SatQuery AI Platform (ChangeFormer Engine)
=================================================================
`;
      const blob = new Blob([dossierContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `SatQuery_ChangeFormer_Report_${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      onClose();
    }, 400);
  };


  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 500,
        background: 'rgba(2, 6, 18, 0.9)',
        backdropFilter: 'blur(20px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '24px',
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="glass-panel"
        style={{
          width: '100%',
          maxWidth: '700px',
          maxHeight: '88vh',
          overflowY: 'auto',
          padding: '32px',
          borderRadius: '16px',
          border: '1px solid rgba(0, 229, 255, 0.4)',
          boxShadow: '0 25px 80px rgba(0, 0, 0, 0.9), 0 0 50px rgba(0, 229, 255, 0.2)',
          position: 'relative',
        }}
      >
        <button
          onClick={onClose}
          style={{
            position: 'absolute',
            top: '20px',
            right: '20px',
            background: 'rgba(255, 255, 255, 0.08)',
            border: 'none',
            color: '#cbd5e1',
            cursor: 'pointer',
            width: '32px',
            height: '32px',
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <X size={16} />
        </button>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
          <div
            style={{
              width: '42px',
              height: '42px',
              borderRadius: '10px',
              background: 'rgba(0, 229, 255, 0.1)',
              border: '1px solid #00e5ff',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#00e5ff',
            }}
          >
            <FileText size={22} />
          </div>
          <div>
            <span className="eyebrow" style={{ margin: 0 }}>
              CHANGEFORMER V6 ANALYSIS REPORT
            </span>
            <h2 style={{ fontSize: '1.35rem', fontWeight: 700, color: '#fff' }}>
              Bi-Temporal Change Detection Dossier
            </h2>
          </div>
        </div>

        {/* Document Preview Box */}
        <div
          style={{
            background: 'rgba(3, 7, 18, 0.8)',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            borderRadius: '10px',
            padding: '24px',
            marginBottom: '24px',
            display: 'flex',
            flexDirection: 'column',
            gap: '16px',
            fontFamily: 'var(--font-sans)',
            fontSize: '0.9rem',
            color: '#cbd5e1',
          }}
        >
          {/* Metadata Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '14px' }}>
            <div>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-mono)', color: 'var(--accent-cyan)' }}>
                MODEL ENGINE
              </div>
              <div style={{ fontWeight: 600, color: '#fff', fontSize: '0.85rem' }}>ChangeFormer V6 (LEVIR)</div>
            </div>
            <div>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-mono)', color: 'var(--accent-cyan)' }}>
                INFERENCE STATUS
              </div>
              <div style={{ fontWeight: 600, color: '#4ade80', fontSize: '0.85rem' }}>Inference Completed</div>
            </div>
            <div>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-mono)', color: 'var(--accent-cyan)' }}>
                TIMESTAMP
              </div>
              <div style={{ fontWeight: 600, color: '#fff', fontSize: '0.85rem' }}>{timestampStr}</div>
            </div>
          </div>

          {/* Metrics Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '10px', background: 'rgba(0, 229, 255, 0.04)', padding: '12px', borderRadius: '8px', border: '1px solid rgba(0, 229, 255, 0.15)' }}>
            <div>
              <div style={{ fontSize: '10px', fontFamily: 'var(--font-mono)', color: '#94a3b8' }}>CHANGED PIXELS</div>
              <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#00e5ff' }}>{changedPixels.toLocaleString()}</div>
            </div>
            <div>
              <div style={{ fontSize: '10px', fontFamily: 'var(--font-mono)', color: '#94a3b8' }}>TOTAL EVALUATED</div>
              <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#ffffff' }}>{totalPixels.toLocaleString()}</div>
            </div>
            <div>
              <div style={{ fontSize: '10px', fontFamily: 'var(--font-mono)', color: '#94a3b8' }}>SURFACE CHANGE</div>
              <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#38bdf8' }}>{changePercentage}%</div>
            </div>
            <div>
              <div style={{ fontSize: '10px', fontFamily: 'var(--font-mono)', color: '#94a3b8' }}>PROB THRESHOLD</div>
              <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#a78bfa' }}>{thresholdVal.toFixed(2)}</div>
            </div>
          </div>

          {/* Resolution, Tiling & Dimensions */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', fontSize: '11px', color: '#cbd5e1', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '12px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>Input Extent: <strong style={{ color: '#fff' }}>{inputDim}</strong></span>
              <span>Mask Grid: <strong style={{ color: '#fff' }}>{maskDim}</strong></span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>Tiled Inference: <strong style={{ color: isTiled ? '#38bdf8' : '#94a3b8' }}>{tiledDesc}</strong></span>
              <span>Evaluated Grid: <strong style={{ color: '#fff' }}>{totalPixels.toLocaleString()} px</strong></span>
            </div>
          </div>

          {/* Real Mask / Images Mini-Thumbnails */}
          {(beforeImg || afterImg || maskImg) && (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '10px' }}>
              {beforeImg && (
                <div style={{ borderRadius: '6px', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.1)', background: '#020617' }}>
                  <div style={{ fontSize: '9px', fontFamily: 'var(--font-mono)', padding: '4px 8px', background: 'rgba(0,0,0,0.6)', color: '#94a3b8' }}>BEFORE (T1)</div>
                  <img src={beforeImg} alt="Before" style={{ width: '100%', height: '80px', objectFit: 'cover' }} />
                </div>
              )}
              {afterImg && (
                <div style={{ borderRadius: '6px', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.1)', background: '#020617' }}>
                  <div style={{ fontSize: '9px', fontFamily: 'var(--font-mono)', padding: '4px 8px', background: 'rgba(0,0,0,0.6)', color: '#94a3b8' }}>AFTER (T2)</div>
                  <img src={afterImg} alt="After" style={{ width: '100%', height: '80px', objectFit: 'cover' }} />
                </div>
              )}
              {maskImg && (
                <div style={{ borderRadius: '6px', overflow: 'hidden', border: '1px solid rgba(0,229,255,0.3)', background: '#020617' }}>
                  <div style={{ fontSize: '9px', fontFamily: 'var(--font-mono)', padding: '4px 8px', background: 'rgba(0,229,255,0.15)', color: '#00e5ff' }}>CHANGE MASK</div>
                  <img src={maskImg} alt="Mask" style={{ width: '100%', height: '80px', objectFit: 'cover' }} />
                </div>
              )}
            </div>
          )}

          {/* Ground Resolution Notice */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', color: '#94a3b8' }}>
            <Info size={13} color="#38bdf8" />
            <span>Area in km² unavailable — geographic resolution metadata was not provided.</span>
          </div>

          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <span className="tech-tag" style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '11px' }}>
              <Cpu size={12} color="#00e5ff" />
              CHANGEFORMER V6
            </span>
            <span className="tech-tag" style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '11px' }}>
              <CheckCircle size={12} color="#22c55e" />
              REAL MODEL OUTPUT
            </span>
          </div>
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
          <button onClick={onClose} className="btn-secondary" style={{ padding: '8px 20px', fontSize: '0.875rem' }}>
            Close
          </button>

          <button onClick={handleDownload} disabled={downloading} className="btn-primary" style={{ padding: '8px 24px', fontSize: '0.875rem' }}>
            <Download size={15} />
            <span>{downloading ? 'Downloading...' : 'Download Report (.txt)'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
